services:
  - type: web
    name: bina-yonetim
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn config.wsgi:application"
    postDeploy: "python manage.py migrate && python manage.py createusu && python manage.py collectstatic --noinput"
